[package]
name = "null_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.14", features = ["full"] }
